spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/hibia?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  social:
    kakao:
      client_id: 2b540be99e2ee859c6b54078ccee3da3 # 앱생성시 받은 REST API 키
      redirect: /signin
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:8888
server:
  host:
    api: http://localhost:8888
    front: http://localhost:3000
logging:
  level:
    root: warn
    com.example.hibia : DEBUG
file:
  upload:
    location: /Users/82104/Desktop
