spring:
  profile:
    active: local
  messages:
    basename: i18n/exception
    encoding: UTF-8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  jwt:
    secret: hibia
  social:
    kakao:
      client_id: 2b540be99e2ee859c6b54078ccee3da3 # 앱생성시 받은 REST API 키
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me
  url:
    base: http://localhost:8888
server:
  port: 8888
logging:
  level:
    org:
      springframework:
        security: DEBUG
