spring:
  profile:
    active: local
  messages:
    basename: i18n/exception
    encoding: UTF-8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  jwt:
    secret: hibia
server:
  port: 8888
logging:
  level:
    org:
      springframework:
        security: DEBUG
