spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://localhost:3306/hibia?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  url:
    base: http://localhost:8888
server:
  host:
    api: http://localhost:8888
    front: http://localhost:3010
logging:
  level:
    root: warn
    com.example.hibia : DEBUG
file:
  upload:
    location: /Users/82104/Desktop
