spring:
  profiles: dev
  datasource:
    url: jdbc:mariadb://52.78.16.92:3306/elbo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: elbo
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  url:
    base: http://52.78.16.92:8888
server:
  host:
    api: http://52.78.16.92:8888
    front: http://52.78.16.92:3000
logging:
  level:
    root: warn
    com.example.hibia: info
  path: /home/ubuntu/hibia/log
  file:
    max-history: 7
